# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 542)
        Dialog.setStyleSheet("background-color: rgb(35, 39, 45);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.label_login = QtWidgets.QLabel(Dialog)
        self.label_login.setMinimumSize(QtCore.QSize(291, 51))
        self.label_login.setMaximumSize(QtCore.QSize(291, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 17pt \"Times New Roman\";")
        self.label_login.setAlignment(QtCore.Qt.AlignCenter)
        self.label_login.setObjectName("label_login")
        self.horizontalLayout_4.addWidget(self.label_login)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_usuario = QtWidgets.QLabel(Dialog)
        self.label_usuario.setMinimumSize(QtCore.QSize(120, 30))
        self.label_usuario.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_usuario.setFont(font)
        self.label_usuario.setStyleSheet("border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 17pt \"Times New Roman\";")
        self.label_usuario.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_usuario.setObjectName("label_usuario")
        self.horizontalLayout_3.addWidget(self.label_usuario)
        self.digitar_usuario = QtWidgets.QLineEdit(Dialog)
        self.digitar_usuario.setMinimumSize(QtCore.QSize(520, 30))
        self.digitar_usuario.setMaximumSize(QtCore.QSize(1000, 1000))
        self.digitar_usuario.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.digitar_usuario.setText("")
        self.digitar_usuario.setObjectName("digitar_usuario")
        self.horizontalLayout_3.addWidget(self.digitar_usuario)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_senha = QtWidgets.QLabel(Dialog)
        self.label_senha.setMinimumSize(QtCore.QSize(120, 30))
        self.label_senha.setMaximumSize(QtCore.QSize(1000, 1000))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_senha.setFont(font)
        self.label_senha.setStyleSheet("border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"font: 75 17pt \"Times New Roman\";")
        self.label_senha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_senha.setObjectName("label_senha")
        self.horizontalLayout_2.addWidget(self.label_senha)
        self.digitar_senha = QtWidgets.QLineEdit(Dialog)
        self.digitar_senha.setMinimumSize(QtCore.QSize(520, 30))
        self.digitar_senha.setMaximumSize(QtCore.QSize(1000, 1000))
        self.digitar_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.digitar_senha.setObjectName("digitar_senha")
        self.horizontalLayout_2.addWidget(self.digitar_senha)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 52, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.btn_logar = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logar.sizePolicy().hasHeightForWidth())
        self.btn_logar.setSizePolicy(sizePolicy)
        self.btn_logar.setMinimumSize(QtCore.QSize(400, 60))
        self.btn_logar.setMaximumSize(QtCore.QSize(400, 60))
        self.btn_logar.setStyleSheet("QPushButton{\n"
"    background-color: #2a3137;\n"
"    border-radius: 4px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 75 14pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover{\n"
"     background-color: #333b42;\n"
"}")
        self.btn_logar.setObjectName("btn_logar")
        self.horizontalLayout.addWidget(self.btn_logar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 24, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_login.setText(_translate("Dialog", "Login"))
        self.label_usuario.setText(_translate("Dialog", "Usuário"))
        self.digitar_usuario.setPlaceholderText(_translate("Dialog", "Digite o usuário"))
        self.label_senha.setText(_translate("Dialog", "Senha"))
        self.digitar_senha.setPlaceholderText(_translate("Dialog", "Digite a senha."))
        self.btn_logar.setText(_translate("Dialog", "Salvar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
